### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by ptquang86** [AndreaVitale/av.imageview#10]
[test.zip](https://github.com/AndreaVitale/imageview/files/588676/test.zip)

When a remote photo is loading, if you set another local photo, it show the local photo, then the remote photo replace the local photo.

Steps to reproduce
1. Use a slow network
2. When the remote photo is loading
3. Click Remove button, and the local photo show up
4. When the remote photo is loaded, it replace the local photo

Thanks

**Comment by AndreaVitale** [comment]
@ptquang86  I'll have a look soon. Could you please specify which platform has this problem? Thanks.

**Comment by ptquang86** [comment]
this bug happens on ios. I have not tested on android yet :)

**Comment by AndreaVitale** [comment]
Verified the bug and fixed. A new release is coming soon. Thanks for your feedback!
