### ISSUE TITLE
Not works on Android with 9.1.0

### ISSUE THREAD

**Issue by frodfigu** [AndreaVitale/av.imageview#102]
Hi Andrea,

I'm having this issue:

Requested module not found: AvImageview

on Android with 9.1.0.GA... everything works fine on iOS with the same configuration.

Any solution for this problem?

<img width="335" alt="Captura de pantalla 2020-11-01 a las 23 52 25" src="https://user-images.githubusercontent.com/701116/97819059-1b198580-1c9e-11eb-8584-6dac3c66b7f4.png">

**Comment by m1ga** [comment]
not sure if that is the same issue we've discussed in slack :) Which version are you using? try 5.0.1 (https://github.com/AndreaVitale/av.imageview/releases/tag/Android-5.0.1) and make sure to include it correctly in tiapp.xml in case you use "platform" inside the module tag.
