### ISSUE TITLE
[AVImageView - Android 5.0.1] Exception caused by release method when app shutdown

### ISSUE THREAD

**Issue by jormagar** [AndreaVitale/av.imageview#105]
When the root window uses AVImageView and a back button is pressend an exception is thrown. Depending on the app architecture it could cause different behaviors.

In our apps it causes a freeze in the next app startup blocking the system UI.

Steps to reproduce:

1. Add some AVImageView to root window.
2. Press back button.

Exception logged with Logcat:

> 2020-12-01 14:21:18.616 9327-9327/es.upv.activityTest D/TiBaseActivity: (main) [177789,177864] onBackPressed: exit
> 2020-12-01 14:21:18.640 9327-9327/es.upv.activityTest I/HwSecImmHelper: mSecurityInputMethodService is null
> 2020-12-01 14:21:18.693 9327-9327/es.upv.activityTest D/ActivityThread: Remove activity client record, r= ActivityRecord{df7eaf8 token=android.os.BinderProxy@ce23223 {es.upv.activityTest/es.upv.activityTest.ActivitytestActivity}} token= android.os.BinderProxy@ce23223
> 2020-12-01 14:21:18.759 9327-9369/es.upv.activityTest W/libEGL: EGLNativeWindowType 0x75092c7010 disconnect failed
> 2020-12-01 14:21:19.073 9327-9327/es.upv.activityTest I/APSAnalyticsStore: session.end
> 2020-12-01 14:21:19.085 9327-9327/es.upv.activityTest D/AndroidRuntime: Shutting down VM
> 2020-12-01 14:21:19.094 9327-9356/es.upv.activityTest D/APSAnalyticsService: 1 analytics event(s) queued
> 2020-12-01 14:21:19.096 9327-9356/es.upv.activityTest D/APSAnalyticsService: Attempting to send 1 analytics event(s)
> 2020-12-01 14:21:19.100 9327-9327/es.upv.activityTest E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: es.upv.activityTest, PID: 9327
>     java.lang.RuntimeException: Unable to destroy activity {es.upv.activityTest/org.appcelerator.titanium.TiActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isFinishing()' on a null object reference
>         at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5046)
>         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5065)
>         at android.app.ActivityThread.-wrap6(Unknown Source:0)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
>         at android.os.Handler.dispatchMessage(Handler.java:108)
>         at android.os.Looper.loop(Looper.java:166)
>         at android.app.ActivityThread.main(ActivityThread.java:7425)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
>      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.isFinishing()' on a null object reference
>         at av.imageview.AvImageView.release(AvImageView.java:94)
>         at org.appcelerator.titanium.proxy.TiViewProxy.releaseViews(TiViewProxy.java:521)
>         at org.appcelerator.titanium.proxy.TiViewProxy.releaseViews(TiViewProxy.java:517)
>         at org.appcelerator.titanium.TiBaseActivity.onDestroy(TiBaseActivity.java:1524)
>         at org.appcelerator.titanium.TiActivity.onDestroy(TiActivity.java:91)
>         at android.app.Activity.performDestroy(Activity.java:7604)
>         at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
>         at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5033)
>         at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5065) 
>         at android.app.ActivityThread.-wrap6(Unknown Source:0) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
>         at android.os.Handler.dispatchMessage(Handler.java:108) 
>         at android.os.Looper.loop(Looper.java:166) 
>         at android.app.ActivityThread.main(ActivityThread.java:7425) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by AndreaVitale** [comment]
It should be fixed with #108
