### ISSUE TITLE
Android: RecyclerView ListView not updating images correctly

### ISSUE THREAD

**Issue by m1ga** [AndreaVitale/av.imageview#113]
Starting with 9.3.0.GA I've noticed that the av.imageview module is not correctly updating images inside a ListView (RecyclerView):

<hr/>

**9.2.2.GA: images show correctly**

![Screenshot_20210123-211118](https://user-images.githubusercontent.com/4334997/105613393-8452f580-5dc2-11eb-8c7f-767aadb69586.png)
scrolling up, revealing new items
<hr/>

![Screenshot_20210123-211121](https://user-images.githubusercontent.com/4334997/105613394-84eb8c00-5dc2-11eb-8751-4350235c2e97.png)
showing local and remote images

<hr/>

**9.3.0.GA and 9.3.1**

![Screenshot_20210123-211302](https://user-images.githubusercontent.com/4334997/105613395-85842280-5dc2-11eb-8ea3-8fb0fc152339.png)
scrolling up, new items are missing
<hr/>

![Screenshot_20210123-211023](https://user-images.githubusercontent.com/4334997/105613391-83ba5f00-5dc2-11eb-81c6-7e499d31b6fb.png)
local images are not visible

<hr/>

I'm debugging at the moment to see if it is inside the module or the SDK.

**Comment by m1ga** [comment]
```<Alloy>
<Window>
	<ListView id="lst" defaultItemTemplate="default">
	    <Templates>
	        <ItemTemplate name="default">
				<ImageView ns="AvImageview" bindId="img" borderColor="red" borderWidth="1" width="128" height="128" />
			</ItemTemplate>
	    </Templates>
	    <ListSection>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	        <ListItem img:image="/images/appicon.png"/>
	    </ListSection>
	</ListView>
</Window>
</Alloy>
```

![ezgif-3-1131831b645f](https://user-images.githubusercontent.com/4334997/105637007-655c6e00-5e6b-11eb-9547-347fbb56822d.gif)

tried a different phone, too. Same result. Sometimes after the second compile but very consistent

**Comment by macasfaj** [comment]
Same issue here :(

**Comment by m1ga** [comment]
seems to be some caching/memory issue. 
If I clear the app data/cache it will show the images again. If I kill my app and reload it again the images are gone. Very strange.
Tried to add 
```
options = options.diskCacheStrategy(DiskCacheStrategy.NONE);
options = options.skipMemoryCache(true);
```
but no luck either. Also made a custom Ti SDK with `recyclerview:1.2.0-beta01` and updated glide to `4.12.0` without success

**Comment by m1ga** [comment]
@macasfaj I've posted it over here too: https://github.com/appcelerator/titanium_mobile/discussions/12557
it looks like 10.1.0 master might fix it. Still have to do some more tests.

The version `Thu Mar 04, 2021 8:25:23 AM` from http://builds.appcelerator.com/#master is still broken for me so it looks like something between that and today might have fixed it. Have to do some more tests but I'll close it over here since it looks like to be an issue in the SDK itself

**Comment by arifje** [comment]
Also having this issue, what SDK should I grab to get this fixed? And which module version? 

PS. tried mobilesdk-10.1.0.v20210304082523, does not solve the issue.

**Comment by m1ga** [comment]
@skoften I was using a fresh 10.1.0 master build (>=12th March). I'll upload one for you later so you can test it, too! But be aware that if you are using an Android theme you have to make some changes in 10 :smile:

**Comment by arifje** [comment]
Update; I grabbed the master repo today, but it still doesn't seem to work :-(

**Comment by m1ga** [comment]
@skoften try https://github.com/appcelerator/titanium_mobile/pull/12781
```
Prevent concurrency exception when attempting to load multiple images
    NOTE: This would cause some image views to never load and stay blank
```
ZIP is here: https://github.com/appcelerator/titanium_mobile/actions/runs/818467494
