### ISSUE TITLE
Can't update `image` on ListView

### ISSUE THREAD

**Issue by DouglasHennrich** [AndreaVitale/av.imageview#13]
For some logic reason on my code I have to change the setting for `image` property to controller after I fetch my data from API.

this is my binding property: `logo:image='/images/defaultImage.png'`

on my controller I get all items of my section and then set the image on `item.logo.image = myImage;`

```js
function getImagesAndCache(){

  $.section.getItems().forEach(function(curr, index){

    if(curr.template != 'default') return;

    var defer = Q.defer();

    TiImageCache.checkIfExists(curr.properties.link, defer).then(function(res){

      console.log(res, index);
      curr.logo.image = '/images/defaultImage.png';

      $.section.updateItemAt(index, curr);

    });

  });

}
```

but for some reason, this never works... already tried to set an locally image on that property but still not working. 

PS: on iOS it works just fine, on Android it's not.

`AvImageView version 0.1.5` - Can't update to 6+ yet
`TiSDK 5.5.1.GA`
`Appc-CLI 5.5.1`

Thanks

**Comment by AndreaVitale** [comment]
This bug cannot be reproduced. I tried to update a listitem by simply adding these lines of code:

```
setTimeout(function() {
    var item = list_section.items[0];

    item.photo.image = "/placeholder.png"; //or "http://www.italiangoodnews.com/wp-content/uploads/2014/11/italy-04.jpg"
    list_section.updateItemAt(0, item);
}, 5000);
```

at the bottom of bundled [example app.js](https://github.com/AndreaVitale/imageview/blob/master/android/android/example/app.js) and everything is working fine.

Test your code and if you have any kind of problem let me know. I close this issue for the moment.
