### ISSUE TITLE
"enableZoomControls" properties not working

### ISSUE THREAD

**Issue by Abidhusain** [AndreaVitale/av.imageview#14]
Hi,

Really appreciate about your code. It help me very well.

But, I am facing one issue in it.
My project need image Zoom feature in it. But with your module, "enableZoomControls" properties are not working in it. 

I am facing this issue in Android. I haven't check for iOS for PinchZoom. 

`AvImageView version 2.0.7` - Android
`TiSDK version 6.0.1.GA.` 

Thank you.

**Comment by AndreaVitale** [comment]
Hi @Abidhusain, thanks for your feedback. This property doesn't work for you cause it is not supported. This module doesn't allow you to use any gestures. There are some opensource modules for that like [this](https://github.com/iotashan/TiTouchImageView).

I'll close this issue.
