### ISSUE TITLE
Support for webp

### ISSUE THREAD

**Issue by christianjgreen** [AndreaVitale/av.imageview#15]
Supporting webp would greatly increase the loading speed and performance of applications.

https://developers.google.com/speed/webp/

**Comment by christianjgreen** [comment]
This module seems to support it on Android (Glide) but not iOS. 
SDWebImage can support Webp by doing the following: https://github.com/rs/SDWebImage/issues/1122

**Comment by ffMathy** [comment]
Is this supported @AndreaVitale? It's not clear from these messages, and also the reason why you closed it.
