### ISSUE TITLE
Please Support Custom HTTP headers

### ISSUE THREAD

**Issue by ptquang86** [AndreaVitale/av.imageview#17]
Some image server require addition Custom HTTP headers.
Please support it if possible.
Thank you :)

**Comment by leoafarias** [comment]
@ptquang86 https://github.com/Topener/authenticatedImageView/blob/master/lib/authImage.js You should be able to use the same code to make it work with av.imageview. Also here is the article to into in detail https://medium.com/all-titanium/enhancing-titanium-how-to-use-images-that-require-authentication-2155915990a0

**Comment by ptquang86** [comment]
thank @leoafarias
i will close this ticket.
It's better supported inside this module

**Comment by AndreaVitale** [comment]
Thanks for the feedback, I will try to support this inside the module for both platforms when I have a bit of time.

**Comment by ptquang86** [comment]
@AndreaVitale that's very nice of you to say so 👍
