### ISSUE TITLE
Round ImageView with Glide

### ISSUE THREAD

**Issue by m1ga** [AndreaVitale/av.imageview#18]
Since you are already using Glide you could add a round ImageView parameter for it.
Examples at: 
* http://stackoverflow.com/a/32390715/5193915
* http://stackoverflow.com/a/25806229/5193915

**Comment by ptquang86** [comment]
that would be great (y)

**Comment by AndreaVitale** [comment]
This will be present in the next release, thank you for your feedback and suggestion!
