### ISSUE TITLE
Android seems to lose the auth headers

### ISSUE THREAD

**Issue by rborn** [AndreaVitale/av.imageview#20]
Hi,

I use the module in a listview an after I scroll the requestHeader doesn't seem to be parsed anymore for some reason (I need auth).

UPDATE: more specific - it seems to lose the ones that are "below" the screen. So for the items that are visible the header is there, but for the ones that needs to be rendered it disappears.

Any idea?
Thank you.

BTW - this is a great module 😄

**Comment by AndreaVitale** [comment]
Hi @rborn,
sorry for the enormous delay.

I tested in a sample project and works for me.
Could you please verify it is solved with the latest Android version of the module ([2.1.3](https://github.com/AndreaVitale/imageview/releases/tag/Android-2.1.3))? 

Thanks for your feedback. 
I'll close the issue. Reopen it if is not fixed for you.

**Comment by rborn** [comment]
@AndreaVitale it seems to work fine now. Not sure it was me or your module but it's working. Thanks a lot for the reply and the module of course 🤗

**Comment by AndreaVitale** [comment]
Nice to hear this! You are welcome and thank you too for the feedback and the patience :-)
