### ISSUE TITLE
Don't Know Where Else To Say This ...

### ISSUE THREAD

**Issue by joshualambert** [AndreaVitale/av.imageview#21]
So this is NOT a bug, but I don't see another place to leave feedback. Just wanted to tell the devs that this is one of the best Titanium modules I've ever ran across. So easy to implement, works so well even on Droid. Y'all did a fantastic job. I'd love to buy a beer for whoever is behind this if there's a way to do so.

Thanks again, and for supporting the Appcelerator Titanium community. You rock.

**Comment by mark22** [comment]
Agreed.  Seriously.   for some reason my native Ti.UI.imageviews crash when I animate a window with them in there, but then I know to do my trusty conversion to av.imageView and voila, no more crashes.

**Comment by joshualambert** [comment]
@mark22 Ya, it's multi purpose and awesome. So wish there was a donate link somewhere. Hint hint, @AndreaVitale

**Comment by AndreaVitale** [comment]
Guys, I really thank you and I'm glad to know that you enjoy it! I added a PayPal.me link if you want to donate something as you requested :-)

**Comment by joshualambert** [comment]
Donation sent. Thanks again, @AndreaVitale

**Comment by AndreaVitale** [comment]
Thank you @joshualambert , really really much appreciated!
