### ISSUE TITLE
Applying viewShadowColor property ignores borderRadius

### ISSUE THREAD

**Issue by Brianggalvez** [AndreaVitale/av.imageview#24]
When setting viewShadowColor property to ImageView it ignores borderRadius property.
<img width="292" alt="captura de pantalla 2017-07-04 a las 10 34 45" src="https://user-images.githubusercontent.com/18324872/27821989-733bdf2e-60a4-11e7-93cb-147aaf03257a.png">
<img width="299" alt="captura de pantalla 2017-07-04 a las 10 35 33" src="https://user-images.githubusercontent.com/18324872/27822020-866db20c-60a4-11e7-8db6-9c3af524a1ef.png">

**Comment by AndreaVitale** [comment]
The problem, I think, is related to TiUIView. Try to use the same properties on the native `Ti.UI.ImageView` and you will see the same behavior.
