### ISSUE TITLE
Putting a blob right into this doesn't work like the native ImageView?

### ISSUE THREAD

**Issue by mark22** [AndreaVitale/av.imageview#25]
On my native image views sometimes I need to display a local file which is gotten in to the form of a blob.  When I set this blob as the image on a native imageView it works fine, but on this one it doesn't seem to show anything.

Possible to add this?

Otherwise an incredible module that has saved me many headaches

**Comment by AndreaVitale** [comment]
Mmm it should work with the actual implementation. Let me do a check and I'll let you know if it is a bug or not. Thank you for your feedback!

**Comment by AndreaVitale** [comment]
Could you please verify with the latest version? Thank you :-)
