### ISSUE TITLE
It doesn't render image even `loadingIndicator:false` in Android Listview item template.

### ISSUE THREAD

**Issue by yomybaby** [AndreaVitale/av.imageview#3]
This is a great module! Thanks!
It works on iOS perfectly, even in Listview item template.

But Android, it doesn't.
I followed your guide. I red a know issue related Android Listview.
(`loadingIndicator : false`)

But AvListview renders nothing on Android list view. (Just blank)

Is there another issue?

alloy.js

``` javascript
var AvImageview = require('av.imageview');
Alloy.Globals.AvImageview = require('av.imageview');
```

myController.js

``` javascript
". itemImg":{
  height: 121,
  width: 100,
  top: 0,
  backgroundColor: "transparent",
  left: 2,
  right: 2,
  contentMode : Alloy.Globals.AvImageview.CONTENT_MODE_ASPECT_FILL,
  loadingIndicator : false
}
```

myController.css

``` xml
...
<Templates> 
    <ItemTemplate name="meetupItem" class="meetupItem">
        <View class="itemWrap">
            <ImageView ns="AvImageview" class="itemImg" bindId="img0"></ImageView>
        <View>
    </ItemTemplate>
</Templates> 
...
```

**Comment by imobicloud** [comment]
Same here, it works great on ios
For Android, it show error
Uncaught ReferenceError: AvImageview is not defined

**Comment by yomybaby** [comment]
@imobicloud  You can remove `Uncaught ReferenceError: AvImageview is not defined` error. Add below code in `alloy.js`.  But it render notthing it works as just `View`.

```
var AvImageview = require('av.imageview');
```

If you find a way to use this module in Android Listview, please let me know~ 👍 

@AndreaVitale , Do you know this issue? 😄

**Comment by AndreaVitale** [comment]
Yeah I know that on Android it doesn't work but at the moment I'm unable to fix this.
Anyway if you need a workaround you can declare a `ScrollableView` inside your ItemTemplate and, for example if you are using a model-view binding, in your `dataTransform` function you can do something like this:

`yourmodel.cover = [require('av.imageview').createImageView({ --- })];`

and bind your `cover` to the `views` property of the `ScrollableView`.

Here is a working example made on my app:

inside **controller.xml**

```
<ListView id="EventList" defaultItemTemplate="event">
    <Templates>
        <ItemTemplate id="Template" name="event">
            <View id="Container">
                <ScrollableView id="Landing" bindId="landing"></ScrollableView>
                <!-- Other views -->
            </View>
        </ItemTemplate>
    </Templates>

    <ListSection dataCollection="event" dataTransform="transformEvent" dataFilter="filterEvents">
        <ListItem itemId="{id}" landing:views="{cover}" />
    </ListSection>
</ListView>
```

inside **controller.js**

```
function transformEvent(model) {
    var event = model.toJSON();

    event.cover = [require("helper").createImageView({
        width: Ti.UI.FILL,
        height: 150,
        image: event.image,
        defaultImage: '/template/event.png'
    })];

    return event;
}
```

**Comment by yomybaby** [comment]
@AndreaVitale  Thanks for your answer!  👍 
When I have a free time, I'll try to fix this too.
If you have any clue to fix this, please let me know about that. 
I don't know how listview work with ImageView. 😄
