### ISSUE TITLE
Loading indicator not working on iOS11

### ISSUE THREAD

**Issue by macasfaj** [AndreaVitale/av.imageview#31]
I've updated my iPhone to iOS11 and loading indicator is not working anymore.

Any help with that, please?

Thanks.

**Comment by AndreaVitale** [comment]
Which sdk are you using? I run an app that uses this module on an iPhone 7 with iOS 11 and the loading indicator appears.

**Comment by macasfaj** [comment]
6.2.2GA & Xcode9

Thanks!

**Comment by AndreaVitale** [comment]
I can confirm you that with the latest SDK/Xcode version the module is working fine. Check your configuration and in case you have other related issues, reopen this one. Thanks for your feedback.
