### ISSUE TITLE
Example listView (without Alloy views)

### ISSUE THREAD

**Issue by arifje** [AndreaVitale/av.imageview#33]
Hi,

Can we get an example for a implementation in a listView if no views are defined in Alloy? We have the templates structure in the TSS file, so no views.

![screen shot 2017-10-07 at 13 18 06](https://user-images.githubusercontent.com/1286410/31307303-fb01964e-ab61-11e7-878c-7b0151540aad.jpg)

**Comment by AndreaVitale** [comment]
Always look at the example directory:
https://github.com/AndreaVitale/av.imageview/blob/master/ios/example/app.js#L29

**Comment by rotechcr** [comment]
Hi,
Following the example when I try to load the library in Android it says "**AvImageview is not defined**", in iOS this doesn't happen, the library loads into the template without problems.
I have checked and the library is installed and working for both platforms.
