### ISSUE TITLE
New iOS release zip file is 4 bytes (incomplete file)

### ISSUE THREAD

**Issue by arifje** [AndreaVitale/av.imageview#36]
![screen shot 2017-10-30 at 11 52 21](https://user-images.githubusercontent.com/1286410/32167403-0b95c836-bd69-11e7-8e01-4106546a1ae8.jpg)

**Comment by AndreaVitale** [comment]
Could you please try the latest one? Thanks.

**Comment by arifje** [comment]
Works now, thanks!

**Comment by AndreaVitale** [comment]
Thank you for your feedback :-)
