### ISSUE TITLE
Module not working with Titanium 7.0.0 GA

### ISSUE THREAD

**Issue by yahya-uddin** [AndreaVitale/av.imageview#38]
This module doesn't seem to work using the new Titanium 7.0.0 GA.

When I compile my app using the following:

    $ appc build -p android

I get the following error:

```
[ERROR] Found incompatible Titanium Modules:
[ERROR]    id: av.imageview      version: 2.2.0  platform: android       min sdk: 6.0.0.GA
[ERROR]    id: av.imageview      version: 2.1.3  platform: android       min sdk: 6.0.0.GA
[ERROR]    id: av.imageview      version: 2.1.2  platform: android       min sdk: 6.0.0.GA
[ERROR]    id: av.imageview      version: 2.1.3  platform: android       min sdk: 6.0.0.GA
[ERROR]    id: av.imageview      version: 2.1.2  platform: android       min sdk: 6.0.0.GA
```

Note that it seems to work fine for older SDK versions such as 6.3.0GA.

I believe it just needs recompiling.

Can you please fix asap!

**Comment by yahya-uddin** [comment]
Looks like it's linked to this:
https://github.com/AndreaVitale/av.imageview/pull/37

**Comment by AndreaVitale** [comment]
Test the zip in #37 and let me know.

**Comment by AndreaVitale** [comment]
You can use [this version](https://github.com/AndreaVitale/av.imageview/blob/master/releases/av.imageview-android-3.0.0.zip) of the module. I tested it right now and is working fine.
I close the issue. Reopen it if you have other related issue.

**Comment by yahya-uddin** [comment]
Great Thanks! :-)
