### ISSUE TITLE
Android version wont install

### ISSUE THREAD

**Issue by thejoshualewis** [AndreaVitale/av.imageview#39]
installing the same as other modules (in the project or sdk home), module is not selectable in the list and doesnt load when manually adding it in tiapp.xml

**Comment by m1ga** [comment]
Which Titanium SDK version are you using? If you are using Ti 7 have a look at: https://github.com/AndreaVitale/av.imageview/pull/37

**Comment by thejoshualewis** [comment]
I tried it on the 6x and 5x.  Doesn’t even appear in the tiapp if you use the GUI to install or if you add it manually

**Comment by m1ga** [comment]
Android 2.2.0 is compatible with 6.x. For 5.x you have to use an older version.
I'm not using Appc Studio but I install it like this:
* Download the right version for SDK
* place the zip in you app main folder (where the tiapp.xml is)
* add `<module>av.imageview</module>` to `<modules>` in tiapp.xml
* use the module
* compile your app (it will extract the zip and use it)

To check it:
`app_name/modules/android/av.imageview` should contain the version you've downloaded.

**Comment by AndreaVitale** [comment]
@thejoshualewis follow the steps that @m1ga reported using the latest version from [here](https://github.com/AndreaVitale/av.imageview/releases/tag/Android-2.3.0) that is built for Ti SDK 6.x.
To install it in an older project with Ti SDK < 6 you have to manually rebuild the module.
Let us know if it works.

**Comment by thejoshualewis** [comment]
Dont suppose anyone has a 5x version that is already compiled?  Appcelerator doesnt really have good instructions on it.

**Comment by m1ga** [comment]
you can dig the history and get and old version:
https://github.com/AndreaVitale/av.imageview/blob/c6d0fa11935625d4036c2bc64cecba21e0b27bf0/releases/av.imageview-android-1.0.6.zip
but it will have all the old bugs :) 

You can clone the repo, change the manifest back to:
```
...
apiversion: 2
architectures: armeabi armeabi-v7a x86
minsdk: 5.0.0
...
```
and run `ti build -p android -b` (or even just `ant` for the old version).

**Comment by thejoshualewis** [comment]
The old version works for me. All I need for a project is the loading animation. Thanks
