### ISSUE TITLE
Android: setImage() keeps the old image

### ISSUE THREAD

**Issue by m1ga** [AndreaVitale/av.imageview#40]
Trimmed version of my XML:

```xml
<Window>
  <ScrollableView>
  <View>
    <ImageView id="img_me" module="av.imageview"/>
    <ImageView id="img_me2"/>
  </View>
  <View></View>
  </ScrollableView>
</Window>
```

```javascript
function updateUser(e) {
	$.img_me.setImage(imgName);
	$.img_me2.setImage(imgName);
}
```

I open a new window (edit) on top of this and call `updateUser()` once the user changes its profile picture (it will even have a new filename). When I close the edit-window and go back to the window with the two images the standard imageview will show the new image, the av.imageview will still show the old image which I even delete (imgName has the new name when I log it). When I reopen the edit-window it will show the new image there. The index window only changes the image when I reopen the whole app.

Setting `enableMemoryCache:false` doesn't change anything. 

*Versions*
Android 7
Ti SDK 7.0.1
patched av.imageview (https://github.com/AndreaVitale/av.imageview/pull/37)

I'll check it with an older version to see if its a problem with ti7, still has to be fixed there if its a bug 😄

**Comment by AndreaVitale** [comment]
I mate! I did a simple test with this code:

XML
```
<ImageView id="Image"
			module="av.imageview"
			top="20"
			width="200"
			height="200"
			contentMode="1"
			backgroundColor="red"
			image="http://t0.gstatic.com/images?q=tbn:ANd9GcT-rgSfqIy93HiXkRq53-XbMlkZsIMoRUIWHpKtPZRbsLeLPY4K"></ImageView>
```
and this js:
```
var images = [
    "http://i0.kym-cdn.com/entries/icons/original/000/024/056/avtr-he-bg-03.jpg",
    "http://nst.sky.it/content/dam/static/contentimages/original/sezioni/cinema/news/2017/04/04/02_Avatar.jpg/jcr:content/renditions/cq5dam.web.738.462.jpeg",
    "https://img.wennermedia.com/article-leads-horizontal/mcdavat_fe057_h-d05796d6-3992-4f1f-a73d-113e83866290.jpg"
];

for (var i = 0; i < images.length; i++) {
    (function(index) {
        setTimeout(function() {
            Ti.API.info("Changing image to", images[index]);

            $.Image.setImage(images[index]);
        }, (index+1)*2000);
    })(i);
}
```
and is working correctly. I can see the issue using `$.Image.image` instead of `$.Image.setImage(--)` ( Issue #41 ) that is now solved.

Could you please verify if it is working for you?

I forgot to tell you that this is working for me on Ti SDK 6.3.0.

**Comment by m1ga** [comment]
Awesome, that fixed the issue! 
For me neither image nor setImage was working but with you fix both are working fine now!

I've updated my PR for Ti SDK 7
