### ISSUE TITLE
Excesive memory usage 

### ISSUE THREAD

**Issue by rlustemberg** [AndreaVitale/av.imageview#42]
When adding remote images, the built in cache manager creates in memory cached data which is not cleared after the setter is called again. In time this could create a huge memory hog. In our use case, av.imageviews where loaded into a Listview. Very soon the app memory usage reaches passes the 1 GB.
Removing the in memory cache of the current image before it's changed solves the issue. 
I'll create a PR for this

**Comment by rlustemberg** [comment]
I've just realised that applying this fix on the current ios version in master is more complicated than what I thought. If we could merge the [#29 user agent and session fix](https://github.com/AndreaVitale/av.imageview/pull/30) then I could PR to that

**Comment by rlustemberg** [comment]
It's just a matter of running ```[[SDImageCache sharedImageCache] removeImageForKey:imageObject fromDisk:NO withCompletion:nil];```

**Comment by AndreaVitale** [comment]
Your PR was merged!! Thank you @rlustemberg !
