### ISSUE TITLE
Can't update image attribute after views are loaded (Android)

### ISSUE THREAD

**Issue by arifje** [AndreaVitale/av.imageview#44]
I can't seem to update the image after the view is loaded. 

When I set the image attribute when the the controller/view is created it works, but when you use a timeout or, in my case, use a remote image URL from a third party API (which I have to load with a XHR request), it won't load.

Example:

```
// update image
setTimeout(function() {
	$.resultImage.image = 'https://cdn.skoften.net/images/65311/pic_007_(1).gif';     
},1000);
```

This results in a empty view. No loading indicator, no defaultImage. 

Platform: Android
SDK: 7.0.1.GA

**Comment by AndreaVitale** [comment]
Are you using the latest version? 
The test case used fixing #40 is the same and it worked.

**Comment by arifje** [comment]
Ah, sorry, works now! :-)
