### ISSUE TITLE
Problems with SDK 7.0.0.GA

### ISSUE THREAD

**Issue by rotechcr** [AndreaVitale/av.imageview#47]
Im getting this error at the App launch: Any Help?

[ERROR] : TiApplication: (main) [13,921] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.moovin.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.moovin.app-1/lib/arm64, /data/app/com.moovin.app-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "**libav.imageview.so**"; Titanium 7.0.1,2017/12/18 10:42,undefined

Seems like it's missing the lib for **arm64-v8a**

**Comment by kerberosargos** [comment]
I am getting same error.

**Comment by m1ga** [comment]
The armeabi-v7a lib folder is missing in the newest release (could be because of a wrong NDK version).

PR and binary 3.1.1:
https://github.com/m1ga/av.imageview/blob/fbeaebb9620620dece18ba2f22d4575903806ea7/releases/av.imageview-android-3.1.1.zip

**Comment by AndreaVitale** [comment]
PR merged. @kerbooo and @rotechcr please try the latest Android dist zip. Reopen the issue if you have other related problems.

**Comment by rotechcr** [comment]
@m1ga @AndreaVitale Thanks a lot for the support!
