### ISSUE TITLE
Android 3.1.1 and iOS-1.4.0 not available on gittio

### ISSUE THREAD

**Issue by yahya-uddin** [AndreaVitale/av.imageview#49]
The latest version of av.imageview: Android 3.1.1 and iOS-1.4.0 is STILL not available on gittio:

http://gitt.io/component/av.imageview

Same applies to quite a few of the newer versions.

Why is this?

**Comment by m1ga** [comment]
judging from the dates at the gitt.io startpage: http://gitt.io/ it looks like it is not updating any module at the moment. Last updated module was `Dec 27, '17`, so shouldn't be related to this module

**Comment by AndreaVitale** [comment]
gitti.io seems to work correctly now :-)
