### ISSUE TITLE
"AvImageview is not defined" trying to load into classic ListView Template in Android

### ISSUE THREAD

**Issue by rotechcr** [AndreaVitale/av.imageview#51]
Hi,
I have followed this classic example:
https://github.com/AndreaVitale/av.imageview/blob/master/ios/example/app.js#L29

But I'm receiving this error "**AvImageview is not defined**" when I try to load the library into a ListView Template in Android using Classic **not Alloy**.
In iOS this doesn't happen, it loads correctly. I have checked and it is installed correctly for both platforms Android & iOS.

I appreciate your help.

**Comment by AndreaVitale** [comment]
Hi @rotechcr , I used the example code to test PRs #52 and #53 . 
Everything is working fine on both platforms.
Could you please paste on a gist the code are you using?
Thanks.
