### ISSUE TITLE
There's no way to remove an existing image or to clear the current image

### ISSUE THREAD

**Issue by prashantsaini1** [AndreaVitale/av.imageview#54]
I was working on an iOS app where I loaded an image from gallery but I also have an option to remove the picture if user wants to. I tried below codes but none of them working and it looks like it's not possible to remove the image. It's for iOS as I tested, not sure if it's the case with Android as well.

`$.imageView.image = '';` and this one also didn't work : `$.imageView.image = null;`

**Comment by m1ga** [comment]
Added `setImage(null)` in this PR too: https://github.com/AndreaVitale/av.imageview/pull/56
But it just adds it for Android

**Comment by yahya-uddin** [comment]
Please create a new release for iOS with the fix. Works on Android fine.

**Comment by m1ga** [comment]
@anik786 the fix was only for Android. So you can't release a new iOS version until someone adds this for iOS too

**Comment by AndreaVitale** [comment]
[e3175c2](https://github.com/AndreaVitale/av.imageview/commit/e3175c22aeab20ee46a1c87ea5de074c126f014f) fixes this issue, thanks to @m1ga for the Android part!

Check the release ios-1.5.1.
