### ISSUE TITLE
Support for animated GIFS (Android)

### ISSUE THREAD

**Issue by christianjgreen** [AndreaVitale/av.imageview#6]
This library uses Glide which handles gifs with the `asGif` method. The current request listener expects a `<String, GlideDrawable>` and will not support gifs. A new request listener should be formed depending on the mimetype of the image being pulled.

```
private String getMimeType(String url) {

        String type = null;

        String extension = MimeTypeMap.getFileExtensionFromUrl(url);

        if (extension != null) {

            type = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);

        }

        return type;

    }
```

If it returns a gif, the RequestListener should create a request with `<String, GifDrawable>` and use the `asGif` method when loading into the imageview.

example:

```
import com.bumptech.glide.load.resource.gif.GifDrawable;

private RequestListener<String, GifDrawable> requestListener;
```

**Comment by AndreaVitale** [comment]
Thank for your suggestions. GIF are now supported in module version 1.0.8 and 2.0.8.

**Comment by ianko** [comment]
:1st_place_medal:
