### ISSUE TITLE
How to implement with listView ItemTemplate on SDK 7.5.0+?

### ISSUE THREAD

**Issue by arifje** [AndreaVitale/av.imageview#62]
![screenshot 2018-12-13 at 16 25 16](https://user-images.githubusercontent.com/1286410/49948478-d773d200-fef3-11e8-8496-260324728f4a.png)

Above shows an example for a listView itemTemplate, but this is not going to work anymore as global scope will be removed in future releases: https://docs.appcelerator.com/platform/latest/?mobile=/guide/Titanium_SDK_7.5.0_Functionality_Update 

How do I use when I can't declare this variable in Alloy.js?

**Comment by kerberosargos** [comment]
Hello same problem is for me too. How can we achieve this issue?

**Comment by hansemannn** [comment]
`<ImageView module="av.imageview" />`

**Comment by AndreaVitale** [comment]
We have no chance, we still have to use `AvImageview` variable in `alloy.js`. 
There are a lot of issue on Jira like this: [TIMOB-24776](https://jira.appcelerator.org/browse/TIMOB-24776). Unfortunately is a Ti issue and it isn't related to this module.
Tested it on 7.5.0.GA 7.5.1.GA and 8.0.0.GA. 
Closing the issue.
