### ISSUE TITLE
Android - Wrong image sizes after orientation change in listView

### ISSUE THREAD

**Issue by arifje** [AndreaVitale/av.imageview#64]
Because a screen cast says it all: https://streamable.com/8fswg

Any way to fix this? I really want images to maintain their FILL / 100% width.

Thanks!

**Comment by hansemannn** [comment]
Same here. We haven't workaround it so far, but setting the width to 100 % (maybe again on rotation) should fix it. In code, it could be fixed by listening to the `frameSizeChanged:bounds:` delegate method of the view.

**Comment by AndreaVitale** [comment]
@hansemannn it works correctly for me on iOS (it already resize on `frameSizeChanged`) [https://streamable.com/5dggu](https://streamable.com/5dggu). 
Could you confirm that? 
I tried with the example `app.js` commited inside both `android` and `ios` module directory.
On Android the issue exists.

**Comment by hansemannn** [comment]
@AndreaVitale You are right, this is an Android only issue!

**Comment by AndreaVitale** [comment]
@skoften could please refer to [my answer](https://github.com/AndreaVitale/av.imageview/issues/63#issuecomment-480753241) in #63 and test the new android module version (4.0.0)?
It is fixed for me.

**Comment by arifje** [comment]
Sorry for the late response, but hereby confirmed this issue is fixed in version 4.0.0, thanks!
