### ISSUE TITLE
iOS - GIFs in Listview freezed (stop looping)

### ISSUE THREAD

**Issue by patriciapg93** [AndreaVitale/av.imageview#67]
Hi,

I have a ListView and I need to display some GIFs in it.

The thing is, the first time, GIFs load and display correctly and if I close the ListView window and reopen it, it still works fine.

But, if I try to append another item, this GIF is freezed and if I close the window and reopen it, the GIFs that loaded before are freezed too.

Any ideas?
Thank you very much.

**Comment by patriciapg93** [comment]
UPDATE: on iOS, even if the GIFs are not in a ListView, they keep freezing after some time. The first time I open the app, they work fine, but then I start navigating through windows and when I return to the window containing the GIFs, they are freezed.

Then if I close the app and reopen it, they work again untill they are freezed again and its always like this.

Our whole app is based on GIFs and images, so we need this to work.

Please can someone help us?
Thank you,

**Comment by AndreaVitale** [comment]
@patriciapg93 have you tested it using TableView instead of ListView?

**Comment by patriciapg93** [comment]
Yes, but same result. GIFs are freezing even if they are inside of a <View>, after some time.

**Comment by AndreaVitale** [comment]
Maybe GIFs are too heavy? Really don't know. Please provide a reproducible test case with a sample app

**Comment by perdona** [comment]
My gifs don't animate on iOS either. Neither inside a listView or outside.
