### ISSUE TITLE
glide causing console warnings [GIF]

### ISSUE THREAD

**Issue by remoloaiza** [AndreaVitale/av.imageview#71]
It seems like glide is causing this log to show a lot:

[WARN] :   Bitmap: Called reconfigure on a bitmap that is in use! This may cause graphical corruption!

The usage was in the view:
`<ImageView id="img_load" module="av.imageview" />`

TSS:
`"#img_load": {
	left : '10%',
	width: 32,
	height: 32,
	image: '/images/loading.gif'
}`

I looked into it and I am not sure how to solve it. Also it appears to show up randomly. I haven't been able to consistently reproduce this, but it even shows up when the Window (with the gif) is closed. I think adding some Glide.clear()s might do it but I can't seem to fix it from the library code.

Also just FYI I think it's safe to ignore it. It's just very annoying to flood the console.

**Comment by AndreaVitale** [comment]
@remoloaiza please refer to my [latest answer here](https://github.com/AndreaVitale/av.imageview/issues/63#issuecomment-480753241) and test the latest android 4.0.0 module version. It is a complete rewrite and this warning should disappear.

**Comment by remoloaiza** [comment]
Great! Ill give it a try as soon as possible!
