### ISSUE TITLE
feat: add support for "autorotate"

### ISSUE THREAD

**Issue by hansemannn** [AndreaVitale/av.imageview#74]
How do you guys handle rotated images with this amazing module? We currently see issues displaying those and would be interested in  either supporting this as a  properly here (like Ti.UI.ImageView) or via pre-processing. Thank you!

**Comment by m1ga** [comment]
according to https://github.com/bumptech/glide/pull/3444#issuecomment-447421962 it will already autorotate based on the exif information.
Check the image if it actually has EXIF infos. Some manufacturer store data in strange ways which makes it hard to find the proper orientation on different devices

**Comment by hansemannn** [comment]
The version linked (merged December 5) is not used in AV.ImageView so far I think, but maybe latest master does! I have to try.

**Comment by m1ga** [comment]
the lnked issues add a custom rotation to glide. They just mention in the ticket that it is already using exif `Glide will already parse exif and rotate images according to the exif.`. I didn't test the images from  https://github.com/recurser/exif-orientation-examples yet
**edit:** all portrait images from the repo are displayed correctly with av.imageview. The normal ImageView will fail sometimes (even with autorotate true!)

**Comment by AndreaVitale** [comment]
I close this issue, the latest versione as you know uses glide 4.9.0 and exif should be correctly handled. Reopen this if this is not working as expected.
