### ISSUE TITLE
assets images

### ISSUE THREAD

**Issue by pburel** [AndreaVitale/av.imageview#8]
unable to load asset image
ex: "/images/pict@2x.png"

as well as image, defaultImage, brokenLinkImage

Titanium 5.5.1.GA

Any explanation ?

**Comment by leoafarias** [comment]
@pburel There is no need to use @2x at the end of the file name for titanium. Titanium will automatically look for the proper image in the assets folder.

**Comment by AndreaVitale** [comment]
@pburel as @leoafarias said, you don't have to specify which specific resolution asset to use. Pick the latest module version and let me know if you have problems. 
Closing this ticket.

**Comment by pburel** [comment]
Sorry. Thanks for replying. 
Pascal
