### ISSUE TITLE
defaultImage and brokenImage properties doesn't works on Android

### ISSUE THREAD

**Issue by juanagu** [AndreaVitale/av.imageview#81]
Hi!
The android module have the properties default and broken image?

The current code in the master branch is this:
`
@Kroll.proxy(creatableInModule= ImageViewModule.class, propertyAccessors = {
        "requestHeaders", "handleCookies", "contentMode", "rounded", "animated", "timeout",
        "shouldCacheImagesInMemory", "loadingIndicator", "loadingIndicatorColor", "image",
        "signature"
})
...
`

**Comment by m1ga** [comment]
Check the documentation at https://github.com/AndreaVitale/av.imageview#api

it is `brokenLinkImage` and `defaultImage` and they are defined here:
https://github.com/AndreaVitale/av.imageview/blob/847d93fc5a30ead8f9472156ba7d8381e3fe03fb/android/src/av/imageview/AvImageView.java#L127

**Comment by juanagu** [comment]
> Check the documentation at https://github.com/AndreaVitale/av.imageview#api
> 
> it is `brokenLinkImage` and `defaultImage` and they are defined here:
> https://github.com/AndreaVitale/av.imageview/blob/847d93fc5a30ead8f9472156ba7d8381e3fe03fb/android/src/av/imageview/AvImageView.java#L127

Hi @m1ga, thanks for the answer, but I tried set the defaultImage and the brokenLinkImage but doesnt works on Android(v4.0.1), works fine on iOS (v2.0.0). 
I tested the behaviour on an empty project and only works if the default and brokenLink are settings in the xml.

index.xml
```
<Alloy>
	<Window class="container" onOpen="doOpen">
		<View layout="vertical" width="Ti.UI.FILL" height="Ti.UI.FILL" top="50">
			<ImageView height="100" width="100" image="/images/avatar_profile_man.jpg" />
			<ImageView height="100" width="100" image="https://this.is.a.broken.link.com/image.png"  defaultImage="/images/avatar_profile_man.jpg" brokenLinkImage="/images/avatar_profile_man.jpg" module="av.imageview" top="20"/>
			<ImageView height="100" width="100" image="/images/avatar_profile_man.jpg" module="av.imageview" top="20"/>
			
			<ImageView id="image" height="100" width="100" module="av.imageview" top="20"/>
			
			<ImageView id="image2" height="100" width="100" module="av.imageview" top="20"/>
		</View>
	</Window>
</Alloy>
```

index.js
```
function doOpen(){
 $.image.brokenLinkImage="/images/avatar_profile_man.jpg";
 $.image.defaultImage="/images/avatar_profile_man.jpg";
 $.image.image="https://this.is.a.broken.link.com/image.png";
 
 $.image2.applyProperties({
 	brokenLinkImage:"/images/avatar_profile_man.jpg",
 	defaultImage:"/images/avatar_profile_man.jpg",
 	image: "https://this.is.a.broken.link.com/image.png"
 });;
}

$.index.open();
```

The result (iOS left, Android right)

<img width="739" alt="Screen Shot 2020-01-20 at 10 05 07" src="https://user-images.githubusercontent.com/4689126/72728741-cec8e300-3b6c-11ea-9fac-687b990bf892.png">

**Comment by AndreaVitale** [comment]
@juanagu `applyProperties` doesn't preserve the properties order. 
The `defaultImage` and `brokenLinkImage` must be set before the `image` and using `applyProperties` this doesn't happen.

So set `defaultImage` and `brokenLinkImage` at creation time.
Please use the [latest version](https://github.com/AndreaVitale/av.imageview/releases/tag/Android-5.0.0) that our ninja @m1ga fixed!
