### ISSUE TITLE
av.imageview inside ItemTemplate 

### ISSUE THREAD

**Issue by fede1295** [AndreaVitale/av.imageview#82]
As per documentation I wrote this:

`<ListView id="Images" defaultItemTemplate="template">
        <Templates>
            <ItemTemplate name="template" height="160">
                <ImageView ns="AvImageview" bindId="photo" height="160" width="Ti.UI.FILL" loadingIndicator="true"  contentMode="Alloy.Globals.CONTENT_MODE_FILL"/>
            </ItemTemplate>
        </Templates>    
</ListView>`

I always get the same error:

`[ERROR] :  TiExceptionHandler: (main) [248,11451] ti:/listview.js:93
[ERROR] :  TiExceptionHandler:   parentProxy = parentProxy[segments[i]];
[ERROR] :  TiExceptionHandler:                             ^
[ERROR] :  TiExceptionHandler: TypeError: Cannot read property 'imageview' of undefined
[ERROR] :  TiExceptionHandler:     at lookupProxyConstructor (ti:/listview.js:93:29)
[ERROR] :  TiExceptionHandler:     at lookup (ti:/listview.js:126:13)
[ERROR] :  TiExceptionHandler:     at processChildTemplates (ti:/listview.js:56:28)
[ERROR] :  TiExceptionHandler:     at UI.createListView (ti:/listview.js:22:6)
[ERROR] :  TiExceptionHandler:     at UIWrapper.invoker [as createListView] (ti:/invoker.js:105:19)
[ERROR] :  TiExceptionHandler:     at new Controller (eval at Module._compile (/app.js:727:16), <anonymous>:105:79)
[ERROR] :  TiExceptionHandler:     at Object.exports.createController (eval at Module._compile (/app.js:727:16), <anonymous>:431:10)
[ERROR] :  TiExceptionHandler:     at modeView (eval at Module._compile (/app.js:727:16), <anonymous>:366:26)
[ERROR] :  TiExceptionHandler:     at eval (eval at Module._compile (/app.js:727:16), <anonymous>:149:9)
[ERROR] :  TiExceptionHandler:     at Object.onLoad (eval at Module._compile (/app.js:727:16), <anonymous>:96:5)
[ERROR] :  V8Exception: Exception occurred at ti:/listview.js:93: Uncaught TypeError: Cannot read property 'imageview' of undefined`

Does anyone know how to help me? thank you

**Comment by m1ga** [comment]
First: it would be way easier to read if you format your code correctly!

Please have a look if you use lower-case `imageview` somewhere. The XML part looks right and I'm using it like this too.

**Comment by AndreaVitale** [comment]
Don't forget to declare `AvImageview` inside your `alloy.js` as explained in the README. 
It works fine also for me.
If you have a reproducibile test case, provide it and we can have a look.
