### ISSUE TITLE
How can I add av.imageview into an ScrollableView?

### ISSUE THREAD

**Issue by frodfigu** [AndreaVitale/av.imageview#84]
Hello, this module is awesome! Congratulations for your work.

I'm trying to add av.imageviews dinamically into my controller.js but I don´t know how can I do this with javascript code.

Any example?

**Comment by m1ga** [comment]
```
var img = require("av.imageview").createImageView({
	image: "image.jpg",
	width: 100,
	height: 100,
	contentMode: Alloy.Globals.CONTENT_MODE_FILL
})
$.scoller.add(img);
```
