### ISSUE TITLE
Cannot load image from application data directory

### ISSUE THREAD

**Issue by sanmanborate** [AndreaVitale/av.imageview#86]
Downloaded & stored image in the application data directory. 
Provided file to load image as follows
`$.idOfImageView.image = fileObj;`

Titanium image-view loads image from the file object, av.imageview fails to load image

**Comment by m1ga** [comment]
working fine here:
```
var xhr = Ti.Network.createHTTPClient({
		onload: function() {
			var file = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, 'mygraphic.png');
			file.write(this.responseData); // write to the file
			$.idOfImageView.image = file.nativePath
			console.log("done", file.nativePath);
		},
		timeout: 10000
	});
	xhr.open('GET', 'https://i.picsum.photos/id/374/536/354.jpg');
	xhr.send();
```
Android 10, Ti SDK 9.0.1

**Comment by sanmanborate** [comment]
@m1ga can you share image view properties? xml or code? also did it work on iOS?

**Comment by m1ga** [comment]
just `<ImageView id="idOfImageView" module="av.imageview"/>`
only tested Android but I use it in other apps like this on iOS too

**Comment by Brianggalvez** [comment]
in iOS, SDK 9.0.1 GA seeing the same error but with local assets.

**Comment by m1ga** [comment]
just tested it on **iOS** 8.3.1.GA, 9.0.0.GA, 9.0.1.GA and 9.0.2: **only 8.3.1.GA works**! Very strange

edit: `<use-app-thinning>false</use-app-thinning>` seems to fix it!

**Comment by AndreaVitale** [comment]
We had a similar issue in the past when app thinning was introduced. Maybe something was changed.

**Comment by AndreaVitale** [comment]
Someone could please test this version? For me is working. Tested on Ti SDK 8.3.1.GA, 9.0.1.GA and 9.1.0 (latest build from repo) with this code:

```
const number = Math.round(Math.random() * 100);
const url = `https://dummyimage.com/400x800&text=${number}`;
const xhr = Ti.Network.createHTTPClient({
	onload: function() {
		let file = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, 'test.png');
		
		file.write(this.responseData);
		Ti.API.info("done", file.nativePath);

		$.Overlay.image = file.nativePath

		file = null;
	},
	timeout: 10000
});

Ti.API.info('Trying to fetch and store image at url', url);

xhr.open('GET', url);
xhr.send();
```

where in my xml I have `<ImageView id="Overlay" module="av.imageview"></ImageView>` and this inside the *tiapp.xml* `<use-app-thinning>true</use-app-thinning>`.

[av.imageview-iphone-2.0.2.zip](https://github.com/AndreaVitale/av.imageview/files/4623515/av.imageview-iphone-2.0.2.zip)

**Comment by m1ga** [comment]
tested it with my project, looking good! Images are visible with 9.0.1.GA and av 2.0.2.

**Comment by AndreaVitale** [comment]
Nice! Thank you guys! 
Version [2.0.2](https://github.com/AndreaVitale/av.imageview/releases/tag/iOS-2.0.2) has been released!
