### ISSUE TITLE
ContentMode aspectRatio

### ISSUE THREAD

**Issue by caspahouzer** [AndreaVitale/av.imageview#9]
Hey there,

I got a missing contentMode like CONTENT_MODE_ASPECTRATIO where just one item (width or height) has to be given.

It would be awesome if you can add it.

**Comment by caspahouzer** [comment]
Great to see you are working again on it. Maybe I can push this ticket? :-)

**Comment by AndreaVitale** [comment]
What you are looking  @for is the `CONTENT_MODE_ASPECT_FIT` that is enabled by default if you don't specify which contentMode you want to use. Here is an example of - I think - your use case:

```
var window = Ti.UI.createWindow({
    backgroundColor: "white"
});

window.add(Ti.UI.createView({
    width: Ti.UI.SIZE,
    height: Ti.UI.SIZE,
    layout: "vertical"
}));

window.children[0].add(AvImageview.createImageView({
    image: "http://www.nationalgeographic.com/content/dam/photography/photos/000/060/6018.ngsversion.1467254523217.adapt.1900.1.jpg",
    width: 100,
    height: Ti.UI.SIZE
}));

window.children[0].add(AvImageview.createImageView({
    top: 20,
    image: "http://www.nationalgeographic.com/content/dam/photography/photos/000/060/6018.ngsversion.1467254523217.adapt.1900.1.jpg",
    width: Ti.UI.SIZE,
    height: 100
}));

window.open();
```

And this the result:

![Screenshot](http://oi68.tinypic.com/rr47dk.jpg)

**Comment by AndreaVitale** [comment]
I will close this ticket. If you have any problem reopen it.
