### ISSUE TITLE
nil host used in call to allowsSpecificHTTPSCertificateForHost

### ISSUE THREAD

**Issue by caspahouzer** [AndreaVitale/av.imageview#97]
Getting this info on iOS 14
```
[INFO]  nil host used in call to allowsSpecificHTTPSCertificateForHost
[INFO]  nil host used in call to allowsAnyHTTPSCertificateForHost:
```
and NO image using this remote image 
`http://badoeynhausen.lightapps.de/wp-content/uploads/2020/09/csm_rathaus-politik-verwaltung_97a1d014c0-e1600237822191.jpg`

Removing `ns="AvImageview"` in 
```
<ImageView image="$.args.image" class="w-screen h-auto rounded-lg" loadingIndicator="true" contentMode="Alloy.Globals.CONTENT_MODE_FILL" brokenLinkImage="/images/placeholder.jpg"/>
```
let the image appear

**Comment by arifje** [comment]
same issue here!

**Comment by caspahouzer** [comment]
Solved via https://github.com/AndreaVitale/av.imageview/releases/tag/iOS-2.1.1

**Comment by arifje** [comment]
Using 2.1.1 but still got this issue;

![Screenshot 2020-10-03 at 10 30 01](https://user-images.githubusercontent.com/1286410/94987001-8cf99480-0563-11eb-839d-741e7c9345b6.jpg)

Only difference is that the images are loaded, but the info keeps showing.
